# Generated by Django 4.1.3 on 2022-11-17 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['id']},
        ),
    ]
